apiVersion: apps/v1
kind: Deployment
metadata:
  name: bludo-app
  labels:
    app: bludo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bludo
  template:
    metadata:
      labels:
        app: bludo
    spec:
      serviceAccountName: sa-bludo
      containers:
      - name: bludo
        image: ghcr.io/bludoco/bludo:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 60
          periodSeconds: 20
        ports:
          - containerPort: 4000
          - name: epmd
            containerPort: 4369
            protocol: TCP
        env:
{{ include "env" . | indent 10 }}
