services:
  db:
    image: postgres:15
    volumes:
      - "bludo-db:/var/lib/postgresql/data"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "bludo"
        - "-U"
        - "bludo"
      retries: 3
      timeout: 5s
    environment:
      POSTGRES_PASSWORD: bludo
      POSTGRES_USER: bludo
      POSTGRES_DB: bludo
    networks:
      - bludo-net
  app:
    build: .
    ports:
      - 4000:4000
    volumes:
      - "bludo-uploads:/app/uploads"
    healthcheck:
      test: curl --fail http://localhost:4000 || exit 1
      retries: 3
      start_period: 20s
      timeout: 5s
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bludo-net

volumes:
  bludo-db:
    driver: local
  bludo-uploads:
    driver: local

networks:
  bludo-net:
    driver: bridge
